debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: '123456'
  database: test
meilisearch:
  api_url: http://192.168.123.205:7700
  api_key:
  insert_size: 1000
  insert_interval: 10
sync:
  - table: test
    index: test
    full: true
    fields:
      id:
      age:
sentry:
  dsn: ''
  environment: 'production'
